### ISSUE TITLE
黑色模式下某些主题的引用内容可读性差

### ISSUE THREAD

**Issue by equationzhao** [geekeditor/geekeditor-releases#1]
太空蓝: ![image](https://user-images.githubusercontent.com/75521101/132984143-04a67c7d-f285-44c0-95e9-ed8b87ce67b8.png)

极客黑: ![image](https://user-images.githubusercontent.com/75521101/132984173-fbb96942-83f4-4f30-8aaf-11a0345ee278.png)

**Comment by montisan** [comment]
最新版已优化(主题这块之后迭代还会进行优化)
