### ISSUE TITLE
右边大纲显示不全

### ISSUE THREAD

**Issue by Tukali** [geekeditor/geekeditor-releases#3]
现在右边大纲的地方可以调整大小非常好用，但是这样会导致大纲显示不全，只会显示左边一部分
<img width="1426" alt="CleanShot 2022-07-23 at 15 24 54@2x" src="https://user-images.githubusercontent.com/45891208/180595168-5599656b-9b46-4396-9a5b-b07844572c48.png">
是否能调整即使大纲显示完整，或者说不是先从大纲的位置向右缩减导致大纲缺失，而是从右边空白的地方向左缩减，更直接的直接让整个右边变扁，这样的大纲看着真的很难受

**Comment by montisan** [comment]
下版本优化，目前有点粗放，谢谢多反馈哦~~
